### PR TITLE
README.md update

### PR DESCRIPTION
**Pull request by SuperDragonite2172**
Updates README.md file to include basic information for all craft types.

### CODE REVIEW

**Review by REDSTONENURD — COMMENTED** [review]
I like this but think it's to much as we want to encourage people to learn to read the configs

**Comment by REDSTONENURD** [comment]
We also put info like this on the wiki tab

**Comment by SuperDragonite2172** [comment]
Yes, we do put that kind of information on the wiki, but I feel the wiki is for more in depth information.  What I've done here is made a quick reference page for those that can't understand the configs, or just need a quick refresher.  I don't see much harm in this.

**Comment by REDSTONENURD** [comment]
I believe that it is better for players to ask other for help and I have also put a substantial amount of effort in making the confits easy to understand

**Comment by SuperDragonite2172** [comment]
The choice is ultimately up to Connie.

**Pull request merged**
